/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kursus_bahasa;

/**
 *
 * @author HP
 */
public class FormBiodata extends javax.swing.JFrame {

    /**
     * Creates new form FormBiodata
     */
    public FormBiodata() {
        initComponents();
        setLocationRelativeTo(null); //agar frame di center
        setResizable(false); //agar ukuran frame tdk dpt diubah
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gmbZoni = new javax.swing.JLabel();
        joni = new javax.swing.JLabel();
        gmbFina = new javax.swing.JLabel();
        fina = new javax.swing.JLabel();
        gmbKeke = new javax.swing.JLabel();
        keke = new javax.swing.JLabel();
        gmbAfril = new javax.swing.JLabel();
        april = new javax.swing.JLabel();
        gmbSasa = new javax.swing.JLabel();
        gmb6 = new javax.swing.JLabel();
        gmb7 = new javax.swing.JLabel();
        anisa = new javax.swing.JLabel();
        sasa = new javax.swing.JLabel();
        andin = new javax.swing.JLabel();
        Keluar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(79, 112, 156));

        gmbZoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ZONI (1).jpg"))); // NOI18N
        gmbZoni.setText("jLabel1");

        joni.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        joni.setForeground(new java.awt.Color(245, 239, 231));
        joni.setText("Zhoni Zhonatan Prabowo (22SA21A186)");
        joni.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                joniAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        gmbFina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PINUY (1).jpg"))); // NOI18N
        gmbFina.setText("jLabel2");

        fina.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        fina.setForeground(new java.awt.Color(245, 239, 231));
        fina.setText("Alfina Aura Santika (22SA21A065)");
        fina.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                finaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        gmbKeke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/KEKE (1).jpg"))); // NOI18N
        gmbKeke.setText("jLabel3");

        keke.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        keke.setForeground(new java.awt.Color(245, 239, 231));
        keke.setText("Keke Nurjanah (22SA21A193)");
        keke.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                kekeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        gmbAfril.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/APRIL (1).jpg"))); // NOI18N
        gmbAfril.setText("jLabel4");

        april.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        april.setForeground(new java.awt.Color(245, 239, 231));
        april.setText("Afrilia Wanti Puspita A (22SA21A061)");
        april.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aprilAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        gmbSasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CILOK (1).jpg"))); // NOI18N
        gmbSasa.setText("jLabel5");

        gmb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ANDIN (1).jpg"))); // NOI18N
        gmb6.setText("jLabel2");

        gmb7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ANISA (2).jpg"))); // NOI18N
        gmb7.setText("jLabel1");

        anisa.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        anisa.setForeground(new java.awt.Color(245, 239, 231));
        anisa.setText("Annisa Rahma(22SA21A124)");
        anisa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                anisaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        sasa.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        sasa.setForeground(new java.awt.Color(245, 239, 231));
        sasa.setText("Latifatun Nissa (22SA21A039)");
        sasa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sasaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        andin.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        andin.setForeground(new java.awt.Color(245, 239, 231));
        andin.setText("Andini Diyas Saputri(22SA21A188)");
        andin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                andinAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button_5735775 (2).png"))); // NOI18N
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(gmbFina, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gmbKeke, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(gmbAfril, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(sasa)
                .addGap(29, 29, 29)
                .addComponent(andin)
                .addGap(41, 41, 41)
                .addComponent(anisa)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(fina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keke)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(gmbSasa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(gmb6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(april)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gmb7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(gmbZoni, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keluar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(joni)
                .addGap(335, 335, 335))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Keluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(gmbZoni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gmbFina, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmbKeke, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmbAfril, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(april)
                    .addComponent(keke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gmb7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gmbSasa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gmb6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anisa)
                    .addComponent(andin)
                    .addComponent(sasa))
                .addGap(67, 67, 67))
        );

        gmbZoni.getAccessibleContext().setAccessibleName("");
        gmbFina.getAccessibleContext().setAccessibleName("");
        gmbKeke.getAccessibleContext().setAccessibleName("");
        gmbAfril.getAccessibleContext().setAccessibleName("");
        gmbSasa.getAccessibleContext().setAccessibleName("");
        gmb6.getAccessibleContext().setAccessibleName("");
        gmb7.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joniAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_joniAncestorAdded
        gmbZoni.setVisible(true);
        joni.setText("Zhoni Zhonatan Prabowo (22SA21A186)");
    }//GEN-LAST:event_joniAncestorAdded

    private void finaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_finaAncestorAdded
        gmbFina.setVisible(true);
        fina.setText("Alfina Aura Santika (22SA21A065)");
    }//GEN-LAST:event_finaAncestorAdded

    private void kekeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_kekeAncestorAdded
        gmbKeke.setVisible(true);
        keke.setText("Keke Nurjanah (22SA21A193)");
    }//GEN-LAST:event_kekeAncestorAdded

    private void aprilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aprilAncestorAdded
        gmbAfril.setVisible(true);
        april.setText("Afrilia Wanti Puspita A (22SA21A061)");
    }//GEN-LAST:event_aprilAncestorAdded

    private void anisaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_anisaAncestorAdded
         gmb7.setVisible(true);
         anisa.setText("Annisa Rahma (22SA21A124)");
    }//GEN-LAST:event_anisaAncestorAdded

    private void sasaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sasaAncestorAdded
        gmbSasa.setVisible(true);
        sasa.setText("Latifatun Nissa (22SA21A039)");
    }//GEN-LAST:event_sasaAncestorAdded

    private void andinAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_andinAncestorAdded
         gmb6.setVisible(true);
         andin.setText("Andini Diyas Saputri (22SA21A188)");
    }//GEN-LAST:event_andinAncestorAdded

    private void KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseClicked
       dispose();
    }//GEN-LAST:event_KeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Keluar;
    private javax.swing.JLabel andin;
    private javax.swing.JLabel anisa;
    private javax.swing.JLabel april;
    private javax.swing.JLabel fina;
    private javax.swing.JLabel gmb6;
    private javax.swing.JLabel gmb7;
    private javax.swing.JLabel gmbAfril;
    private javax.swing.JLabel gmbFina;
    private javax.swing.JLabel gmbKeke;
    private javax.swing.JLabel gmbSasa;
    private javax.swing.JLabel gmbZoni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel joni;
    private javax.swing.JLabel keke;
    private javax.swing.JLabel sasa;
    // End of variables declaration//GEN-END:variables
}
